name: "Lint Checker: Onboarding SPA"
on:
  workflow_dispatch:
  push:
    paths:
      - "src/**/*.js"
      - "src/**/*.scss"
  pull_request:
    types: [opened, edited, reopened, ready_for_review]
    paths:
      - "src/**/*.js"
      - "src/**/*.scss"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  lint-check-spa:
    name: Run Lint Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Picks the Node version to be used and installs it
      # https://github.com/actions/setup-node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.2.0'
          cache: 'npm'
      
      # Checks for cache if present
      - name: Cache node_modules directory
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      # Installs wp-script for lint checks
      - name: Install dependencies
        run: npm i @wordpress/scripts@24.3.0
        if: steps.cache.outputs.cache-hit != 'true'

      # Gets the files changed wrt to trunk and searches for js files
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            +(src)/**/*.js

      # Runs wp-script for linting js
      - name: Run JS Lint
        id: js-lint
        run: npx wp-scripts lint-js ${{ env.GIT_DIFF }}
        if: "!! env.GIT_DIFF"

      # Gets the files changed wrt to trunk and searches for css files
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            +(src)/**/*.scss

      # Runs wp-script for linting scss
      - name: Run SASS Lint
        id: sass-lint
        run: npx wp-scripts lint-style ${{ env.GIT_DIFF }}
        if: ${{ (!! env.GIT_DIFF) && (success() || steps.js-lint.conclusion == 'failure') }}
