name: JS Lint
on:
  push:
    branches:
      - '**'
    paths:
      - '**.js'
      - '**.scss'
  pull_request:
    types: [opened, edited, reopened, ready_for_review]
    paths:
      - '**.js'
      - '**.scss'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: Run WordPress JS Lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      # Gets the files changed wrt to trunk and searches for js files
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            +(src)/**/*.js

      # Picks the Node version to be used and installs it
      # https://github.com/actions/setup-node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.2.0'
        if: "!! env.GIT_DIFF"

      # Checks for cache if present
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
        if: "!! env.GIT_DIFF"

      # Installs wp-script for lint checks
      - name: Install @wordpress/scripts dependencies
        run: npm i @wordpress/scripts -g
          
      # Runs wp-script for linting js
      - name: Run wp-scripts lint-js
        run: wp-scripts lint-js ${{ env.GIT_DIFF }}

      # Gets the files changed wrt to trunk and searches for css files
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            +(src)/**/*.scss

      # Runs wp-script for linting scss
      - name: Run wp-scripts lint-style
        run: wp-scripts lint-style ${{ env.GIT_DIFF }}
